### Numpy part2

In [1]:
import numpy as np

#### 4. Operation

In [3]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- sum및 axis

In [6]:
# 모든 요소들의 합
a.sum()

78

In [7]:
# 열의 합
a.sum(axis=0)#열의 합

array([15, 18, 21, 24])

In [9]:
a.sum(axis=1)#행의 합

array([10, 26, 42])

In [10]:
np.sum(a[1])

26

In [13]:
a.min(axis=1), a.min(axis=0)

(array([1, 5, 9]), array([1, 2, 3, 4]))

In [12]:
a.max(axis=1), a.max(axis=0)

(array([ 4,  8, 12]), array([ 9, 10, 11, 12]))

- sorting

In [14]:
b=np.array([[4,3,5,8],[5,7,3,8],[5,7,7,7]])
b

array([[4, 3, 5, 8],
       [5, 7, 3, 8],
       [5, 7, 7, 7]])

In [16]:
np.sort(b)#행 단위로 정렬된다.

array([[3, 4, 5, 8],
       [3, 5, 7, 8],
       [5, 7, 7, 7]])

In [26]:
b=np.array([[4,3,5,8],[5,7,3,8],[5,7,7,7]])
np.sort(b, axis=0)

array([[4, 3, 3, 7],
       [5, 7, 5, 8],
       [5, 7, 7, 8]])

In [25]:
b=np.array([[4,3,5,8],[5,7,3,8],[5,7,7,7]])
b.sort()
b

array([[3, 4, 5, 8],
       [3, 5, 7, 8],
       [5, 7, 7, 7]])

In [34]:
#내림차순
b=np.array([[147,43,35,81],[25,37,43,58],[65,77,87,97]])
np.sort(b)[0][::-1]

array([147,  81,  43,  35])

In [36]:
b=np.array([[147,43,35,81],[25,37,43,58],[65,77,87,97]])
np.argsort(b)#작은순으로 인덱스값을 알려준다.

array([[2, 1, 3, 0],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [43]:
c=np.array([12,33,11,0])
indices = np.argsort(c)
c[indices]

array([ 0, 11, 12, 33])

- Mathematical funcitons

In [44]:
# sigmoid method
def sigmoid(x):
    return 1. / (1+np.exp(-x))

In [47]:
X=np.array([-10,0,10])
sigmoid(X)#메소드 매개변수로 array를 주면, 리턴값으로 array를 받을 수 있다.

array([4.53978687e-05, 5.00000000e-01, 9.99954602e-01])

- Transpose(전치)

In [49]:
b

array([[147,  43,  35,  81],
       [ 25,  37,  43,  58],
       [ 65,  77,  87,  97]])

In [51]:
b.T#행과 열이 바뀌는 것을 전치라고 한다.

array([[147,  25,  65],
       [ 43,  37,  77],
       [ 35,  43,  87],
       [ 81,  58,  97]])

- concatenate, vstacdk, hstack
###### array를 합치는 방법

In [52]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [53]:
b=np.array([[5,6]])
b

array([[5, 6]])

In [59]:
np.vstack((a, b)) , np.concatenate((a,b))

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [60]:
np.hstack((a, b.T)) , np.concatenate((a,b.T), axis=1)

(array([[1, 2, 5],
        [3, 4, 6]]),
 array([[1, 2, 5],
        [3, 4, 6]]))

- 사칙연산

In [61]:
a + a

array([[2, 4],
       [6, 8]])

In [62]:
a - a

array([[0, 0],
       [0, 0]])

In [63]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [64]:
a / a

array([[1., 1.],
       [1., 1.]])

- Broadcasting

In [66]:
a, a + 3

(array([[1, 2],
        [3, 4]]),
 array([[4, 5],
        [6, 7]]))

- Dot product

In [72]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
a, b, np.dot(a,b)#곱셈

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]),
 array([[ 58,  64],
        [139, 154]]))

In [74]:
np.dot(np.array([1,2,3]), np.array([4,5,6])) #1차원일 경우 곱셈 가능

32

### 6.Comparison

- all & any

In [75]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [78]:
np.all(a>5)# 전부 True일 때

False

In [80]:
np.any(a>5)# 하나라도 True일 때

True

- Logical operation

In [87]:
b = np.arange(7,13).reshape(3,2)
print(b)
b = np.logical_and(b>3, b<7)
print(b)

[[ 7  8]
 [ 9 10]
 [11 12]]
[[False False]
 [False False]
 [False False]]


In [88]:
b=np.logical_or(b>3, b<7)
b

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [105]:
a= np.arange(1,21).reshape(4,5)
print(a)
a.argmax(), np.argmax(a)#a.max()와 달리 인덱스 값을 리턴한다.

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


(19, 19)

In [106]:
print(a)
a.argmin(), np.argmin(a), a.min()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


(0, 0, 1)

7. boolean & Fancy indexing

In [99]:
# array a에서 값이 6이상인것만 가져오기 - filtering
a[a>=6]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [136]:
a= np.arange(1,14)
b=np.logical_and(a>3, a<7)

In [137]:
a[b]

array([4, 5, 6])

- fancy indexing

In [120]:
a=np.array([2,3,4,5])
b=np.array([0,0,1,3,2,1])#a의 인덱스 값
a[b]

array([2, 2, 3, 5, 4, 3])

#### 8.기술 통계

In [129]:
a=np.random.randn(10)
a

array([-1.58923836, -0.32289268,  0.81002342,  1.92881654, -0.86376486,
       -0.62821954,  1.1874699 , -0.00855585, -0.7417684 , -3.06429178])

In [130]:
#평균
np.mean(a), a.mean()

(-0.329242159568419, -0.329242159568419)

In [131]:
#표준 편차
np.std(a), a.std()

(1.3569604777539181, 1.3569604777539181)

In [132]:
a.max(), a.min()

(1.9288165443359933, -3.0642917765037114)

In [138]:
# 4분위 수
np.percentile(a,25), np.percentile(a, 50), np.percentile(a, 75)

(4.0, 7.0, 10.0)

In [140]:
np.median(a)

7.0

In [141]:
a=np.random.randint(0,3,100)
a

array([1, 2, 1, 0, 2, 1, 0, 2, 2, 2, 1, 0, 2, 1, 1, 0, 1, 2, 1, 0, 2, 0,
       2, 2, 2, 2, 1, 2, 2, 0, 1, 2, 0, 0, 1, 1, 2, 0, 2, 2, 2, 1, 0, 1,
       2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 0, 1, 2, 0, 0, 0, 2, 0, 2, 0, 0, 1,
       0, 1, 2, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 1,
       0, 2, 2, 2, 1, 2, 0, 0, 2, 2, 1, 1])

In [142]:
np.unique(a)#원소 값을 중복없이 가져온다.

array([0, 1, 2])

In [143]:
np.unique(a, return_counts=True)

(array([0, 1, 2]), array([29, 36, 35], dtype=int64))