In [3]:
import numpy as np

<pre>1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
10 20 30 40
50 60 70 80
</pre>

In [8]:
np.array(([10,20,30,40],[50,60,70,80]), int)
np.arange(10,90,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

<pre>
2. 다음 행렬과 같은 행렬이 있다.
m = np.array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])
1) 이 행렬에서 값 7 을 인덱싱한다.
2) 이 행렬에서 값 14 을 인덱싱한다.
3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
</pre>

In [10]:
m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
#1
m[1][2]

7

In [11]:
#2
m[-1][-1]

14

In [12]:
#3
m[1][1:3], m[1,1:3]

(array([6, 7]), array([6, 7]))

In [26]:
m[1:3,2]

array([ 7, 12])

In [13]:
m[0:2,-2:len(m[0])], m[0:2,-2:]

(array([[3, 4],
        [8, 9]]),
 array([[3, 4],
        [8, 9]]))

<pre>3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
1) 이 배열에서 3의 배수를 찾아라.
2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.</pre>


In [60]:
m = m.reshape(1,-1)
#1
m[m%3==0]

array([ 0,  3,  6,  9, 12])

In [61]:
#2
m[m%4==1]

array([ 1,  5,  9, 13])

In [62]:
#3
m[np.logical_and(m%3==0, m%4==1)]

array([9])

<pre>4. 값을 직접 입력하지 말고
우측의 행렬을 만드시오.
2, 1, 0, 0, 0
3, 2, 1, 0, 0
0, 3, 2, 1, 0
0, 0, 3, 2, 1
0, 0, 0, 3, 2
</pre>

In [68]:
a=np.identity(5, dtype=int)*2+np.eye(5, 5,k=1, dtype=int)+np.eye(5, 5,k=-1, dtype=int)*3
a

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

<pre>5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
대해 다음과 같은 값을 구하시오.
1) 전체의 최댓값
2) 각 행의 합
3) 각 행의 최댓값
4) 각 열의 평균
5) 각 열의 최솟값</pre>

In [14]:
a=np.random.rand(30).reshape(5,6) * 10
a=np.random.uniform(0,10,30).reshape(5,6).round(4)
a

array([[8.318 , 5.023 , 7.0685, 1.177 , 8.74  , 6.8179],
       [7.7341, 2.8457, 9.6991, 5.5067, 7.2152, 4.8056],
       [5.1956, 5.0957, 8.5505, 7.4433, 7.1038, 5.0077],
       [1.326 , 4.106 , 0.5447, 2.7194, 8.7295, 9.0071],
       [3.7642, 5.7552, 6.3604, 0.3099, 9.1405, 2.8752]])

In [80]:
#1
a.max()

9.890691714942879

In [82]:
#2
a.sum(axis=1)

array([26.32504944, 26.36714371, 30.23995893, 33.82009777, 29.5056322 ])

In [83]:
#3
a.max(axis=1)

array([6.1699292 , 7.94970234, 9.11947297, 9.89069171, 8.33637263])

In [84]:
a.mean(axis=0)

array([4.46899884, 6.04798994, 1.82101794, 6.20066494, 5.49153139,
       5.22137336])

In [85]:
a.min(axis=0)

array([0.90977337, 3.37088855, 0.37187166, 0.92566671, 2.55551493,
       2.81843126])

<pre>6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
array([[ 1, 2, 3, 4],
 [ 46, 99, 100, 71],
 [ 81, 59, 90, 100]])
</pre>

In [15]:
c=np.array([[ 1, 2, 3, 4], [ 46, 99, 100, 71], [ 81, 59, 90, 100]])

c[:,np.argsort(c[2])[::-1]]

array([[  4,   3,   1,   2],
       [ 71, 100,  46,  99],
       [100,  90,  81,  59]])

<pre>7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
던져서 나오는 숫자의 평균을 구하시오.
</pre>

In [20]:
np.random.randint(1,7,100).mean()

3.38

<pre>8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%
인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.
</pre>

In [18]:
a=np.random.uniform(-1.0,1.0,250)
stock=10000.0
answer = []
for i in a:
    stock=stock+(stock*i/100)
    answer.append(stock.round(4))
print(answer)

[9904.2106, 9868.0345, 9917.6826, 9913.4697, 10004.2797, 10035.8544, 10039.4448, 10130.9513, 10231.9634, 10225.9402, 10249.5344, 10325.7679, 10276.0739, 10265.7145, 10180.9794, 10146.6634, 10203.5022, 10272.4638, 10219.8525, 10209.0901, 10303.6894, 10318.9643, 10257.8665, 10253.6277, 10328.434, 10344.0782, 10401.1243, 10340.2744, 10420.2534, 10483.8427, 10436.5334, 10394.6955, 10435.1512, 10522.1796, 10431.0256, 10426.2737, 10410.9105, 10469.6951, 10573.6179, 10493.7936, 10543.8351, 10609.3717, 10707.9488, 10636.077, 10638.6864, 10732.386, 10626.7307, 10537.338, 10613.4283, 10530.8076, 10550.2669, 10615.6568, 10586.7291, 10626.619, 10556.4888, 10637.7752, 10577.0241, 10665.0343, 10584.2838, 10598.524, 10624.8359, 10599.2054, 10635.0401, 10602.6834, 10677.6849, 10759.1812, 10770.8359, 10683.8901, 10768.6108, 10730.1712, 10718.5077, 10647.1058, 10689.9915, 10694.5028, 10637.7601, 10694.4891, 10669.6218, 10608.8275, 10623.6205, 10530.3284, 10426.5673, 10483.2074, 10574.5061, 10568.3126, 1