In [2]:
import numpy as np

<pre>1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
10 20 30 40
50 60 70 80
</pre>

In [10]:
np.array(([10,20,30,40],[50,60,70,80]), int)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

<pre>
2. 다음 행렬과 같은 행렬이 있다.
m = np.array([[ 0, 1, 2, 3, 4],
 [ 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14]])
1) 이 행렬에서 값 7 을 인덱싱한다.
2) 이 행렬에서 값 14 을 인덱싱한다.
3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
</pre>

In [12]:
m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
#1
m[1][2]

7

In [13]:
#2
m[-1][-1]

14

In [14]:
#3
m[1][1:3]

array([6, 7])

In [26]:
m[1:3,2]

array([ 7, 12])

In [29]:
m[0:2,-2:len(m[0])]

array([[3, 4],
       [8, 9]])

<pre>3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
1) 이 배열에서 3의 배수를 찾아라.
2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.</pre>


In [60]:
m = m.reshape(1,-1)
#1
m[m%3==0]

array([ 0,  3,  6,  9, 12])

In [61]:
#2
m[m%4==1]

array([ 1,  5,  9, 13])

In [62]:
#3
m[np.logical_and(m%3==0, m%4==1)]

array([9])

<pre>4. 값을 직접 입력하지 말고
우측의 행렬을 만드시오.
2, 1, 0, 0, 0
3, 2, 1, 0, 0
0, 3, 2, 1, 0
0, 0, 3, 2, 1
0, 0, 0, 3, 2
</pre>

In [68]:
a=np.identity(5, dtype=int)*2+np.eye(5, 5,k=1, dtype=int)+np.eye(5, 5,k=-1, dtype=int)*3
a

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

<pre>5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
대해 다음과 같은 값을 구하시오.
1) 전체의 최댓값
2) 각 행의 합
3) 각 행의 최댓값
4) 각 열의 평균
5) 각 열의 최솟값</pre>

In [78]:
a=np.random.rand(30).reshape(5,6) * 10
a

array([[6.1699292 , 3.74481638, 1.23751291, 5.05378767, 4.50673793,
        5.61226535],
       [5.15839899, 3.37088855, 2.06669944, 0.92566671, 6.89578767,
        7.94970234],
       [1.77051999, 8.92506084, 1.65676261, 9.11947297, 5.94971127,
        2.81843126],
       [0.90977337, 9.89069171, 3.77224308, 9.78512865, 2.55551493,
        6.90674603],
       [8.33637263, 4.30849222, 0.37187166, 6.11926872, 7.54990514,
        2.81972184]])

In [80]:
#1
a.max()

9.890691714942879

In [82]:
#2
a.sum(axis=1)

array([26.32504944, 26.36714371, 30.23995893, 33.82009777, 29.5056322 ])

In [83]:
#3
a.max(axis=1)

array([6.1699292 , 7.94970234, 9.11947297, 9.89069171, 8.33637263])

In [84]:
a.mean(axis=0)

array([4.46899884, 6.04798994, 1.82101794, 6.20066494, 5.49153139,
       5.22137336])

In [85]:
a.min(axis=0)

array([0.90977337, 3.37088855, 0.37187166, 0.92566671, 2.55551493,
       2.81843126])

<pre>6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
array([[ 1, 2, 3, 4],
 [ 46, 99, 100, 71],
 [ 81, 59, 90, 100]])
</pre>

In [99]:
c=np.array([[ 1, 2, 3, 4], [ 46, 99, 100, 71], [ 81, 59, 90, 100]])

c[0:3,np.argsort(c[2])[::-1]]

array([[  4,   3,   1,   2],
       [ 71, 100,  46,  99],
       [100,  90,  81,  59]])

<pre>7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
던져서 나오는 숫자의 평균을 구하시오.
</pre>

In [103]:
a=np.random.randint(1,7,100)
a.mean()

3.53

<pre>8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%
인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.
</pre>

In [124]:
a=np.random.uniform(-1.0,1.0,250)
stock=10000.0
answer = []
for i in a:
    stock=stock+(stock*i/100)
    answer.append(stock)
print(answer)

[10025.911150596059, 9982.375340490174, 9886.122498792127, 9892.859946324124, 9950.867281944951, 9902.490883347275, 9890.604034545857, 9805.750327038208, 9863.416879438386, 9862.888730152585, 9780.48542473024, 9757.578557723293, 9788.354466127807, 9838.439834393246, 9841.558976978738, 9800.873499971769, 9875.113370820887, 9931.080311377877, 9992.616820500074, 9937.604424041196, 9978.095497336639, 9933.796818075805, 9881.144416368032, 9976.73891185087, 10050.413467666156, 9977.758351570088, 10063.45734618503, 10011.239884050829, 10097.15266777697, 10038.170548583457, 10068.412417133326, 10161.969193848754, 10212.307781715406, 10173.727109537933, 10200.351321797962, 10237.764638798048, 10293.323191512773, 10190.785824795987, 10256.487391502096, 10338.067601404298, 10423.80532335036, 10481.058964099138, 10432.144314028874, 10425.624764353524, 10457.998598137883, 10468.650787066475, 10490.651903367347, 10533.598038597247, 10636.944475564307, 10542.657268512801, 10636.103573732918, 10567.35